title: "riscv-5: A Pipelined Processor (RV32I)"
author: Charlie Shields
description: A verified 5-stage pipelined RV32I core implemented in SystemVerilog.

header_pages:
  - index.md
  - architecture/manual.md
  - architecture/stages.md
  - architecture/hazards.md
  - verification/report.md
  - developer/guide.md

remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag
- jekyll-sitemap

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  syntax_highlighter: rouge