title: RISC-V Pipelined Processor
description: A verified 5-stage pipelined RV32I core implemented in SystemVerilog.

header_pages:
  - index.md
  - architecture/manual.md
  - verification/report.md
  - developer/guide.md


remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one